// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbHost = process.env.DB_HOST;
const dbPort = process.env.DB_PORT || 4000;
const dbUser = process.env.DB_USER;
const dbPass = process.env.DB_PASSWORD;
const dbName = process.env.DB_NAME;

const buildFallbackUrl = () => {
  if (!dbHost || !dbPort || !dbUser || dbPass === undefined || !dbName) {
    return process.env["DATABASE_URL"] || "";
  }

  const encodedUser = encodeURIComponent(dbUser);
  const encodedPass = encodeURIComponent(dbPass);
  return `mysql://${encodedUser}:${encodedPass}@${dbHost}:${dbPort}/${dbName}?sslaccept=strict`;
};

const shouldReplaceDatabaseUrl = (url?: string) => {
  const normalized = String(url || "").trim().toLowerCase();
  if (!normalized) return true;

  return (
    normalized.includes("user:password@host:port") ||
    normalized.includes("mysql://user:password@host:port/db")
  );
};

const fallbackUrl = buildFallbackUrl();
const datasourceUrl = shouldReplaceDatabaseUrl(process.env["DATABASE_URL"])
  ? fallbackUrl
  : process.env["DATABASE_URL"] || fallbackUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
